appName: ssc
global:
  useTls: true
  useTLSClientAuth: false
  sslCertSecretName: ssl-certs
  createIngress: true

image:
  repositoryPrefix: "nexus-docker-public-hosted.ossim.io/"
  tag: 20.2.0.0149.0001
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

ingressClass: nginx

path: /
routes:
  - hostname: fortify.ossim.io
    servicePort: 80

# overrides service name, defaults to the helm chart name (ssc)
nameOverride: ""

# overrides fully-qualified service, defaults to "{deployment_name}-{service_name}"
fullnameOverride: ""


# service is a map of the Kubernetes service resource options used to expose the SSC service
service:

  # supported values: "ClusterIP", "NodePort", "LoadBalancer"
  type: ClusterIP
  # external HTTP port of the service
  httpPort: 80
  # external HTTPS port of the service (required)
  httpsPort: 443
  # fixed service cluster IP address, if empty, Kubernetes assigns a value
  clusterIP: ""
  # fixed load balancer IP address, if empty, the Kubernetes cloud provider assigns a value
  loadBalancerIP: ""
  #"a10b9f7eaf6c743ca8adfee1b176c47e-09557271432545fc.elb.us-east-1.amazonaws.com"
  # map of annotations applied to the service
  annotations: {}

# urlHost is a fully qualified DNS name for externally accessing the application (required)
urlHost: "fortify.ossim.io"

# jdbcDriverUri is a path to a JDBC driver file or an URL for downloading a JDBC driver (required for Oracle and MySQL)
jdbcDriverUri: ""
  # https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.25/mysql-connector-java-8.0.25.jar

# httpClientCertificateVerification is configuring HTTPS client certificate verification, supported values: "none", "optional", "required"
httpClientCertificateVerification: "none"


# reference to externally managed Kubernetes secret (required)
secretRef:
  # name is a name of externally managed Kubernetes secret to be used for configuration (required)
  name: "sscsecrets"
  # keys is a map of key names for externally managed Kubernetes secret (required)
  keys:
    # sscLicenseEntry is a key name for a Fortify licence (required)
    sscLicenseEntry: "fortify.license"
    # sscAutoconfigEntry is a key name for an SSC autoconfig file (required)
    sscAutoconfigEntry: "ssc.autoconfig.yaml"
    #sscSecretKeyEntry is key name for an SSC secret.key file
    sscSecretKeyEntry: ""
    # httpCertificateKeystoreFileEntry is a key name for a keystore with certificate and private key for HTTPS (required)
    httpCertificateKeystoreFileEntry: "keystore"
    # httpCertificateKeystorePasswordEntry is a key name for a password of the HTTPS keystore (required)
    httpCertificateKeystorePasswordEntry: "keystore-password"
    # httpCertificateKeystorePasswordEntry is a key name for a password of the HTTPS private key (required)
    httpCertificateKeyPasswordEntry: "keystore-password"
    # httpTruststoreFileEntry is a key name for a truststore used by client certificate verification
    httpTruststoreFileEntry: ""
    # httpTruststoreFileEntry is a key name for a password of the client certificate verification truststore
    httpTruststorePasswordEntry: ""
    # jvmTruststoreFileEntry is a key name for a JVM truststore
    jvmTruststoreFileEntry: ""
    # jmvTruststorePasswordEntry is a key name for a password of the JVM truststore
    jmvTruststorePasswordEntry: ""

persistentVolumeClaim:
  size: "4Gi"
  storageClassName: "gp2"
  selector: {}

# environment is a list of additional environment variables for the Pod
environment: []

# jvmMaxRAMPercentage is a percentage of memory limit to be used for JVM heap
jvmMaxRAMPercentage: 86

# Kubernetes Pod resources specification
resources:
  limits:
    cpu: 8
    memory: 28Gi
  requests:
    cpu: 1
    memory: 7Gi

nodeSelector: {}
tolerations: []
affinity: {}
