appProperties:
  host.validation: false
  #host.url: ""

datasourceProperties:
  db.username: 'admin'
  db.password: 'jku87LK76th*&hgu'
  db.driver.class: com.microsoft.sqlserver.jdbc.SQLServerDriver
  db.dialect: com.fortify.manager.util.hibernate.SQLServerDialect
  db.like.specialCharacters: '%_{'
  jdbc.url: 'jdbc:sqlserver://fortify-ssc-v3.cfussmnw2zzg.us-east-1.rds.amazonaws.com;database=ssc;sendStringParametersAsUnicode=false'

seeds:
#modify the path to the appropriate location for your enviroment
  - '/app/seeds/000-fortify/000-Fortify_Process_Seed_Bundle-2020_Q3_0006.zip'
  - '/app/seeds/000-fortify/Fortify_PCI_Basic_Seed_Bundle-2020_Q3_0006.zip'
  - '/app/seeds/000-fortify/Fortify_PCI_SSF_Basic_Seed_Bundle-2020_Q3_0006.zip'
  - '/app/seeds/000-fortify/Fortify_Report_Seed_Bundle-2020_Q3_0006.zip'